### ISSUE TITLE
[2pts]Ruby Capstone : Setup Kanban Board & Assign Cards

### ISSUE THREAD

**Issue by Tekhlay** [ohyajk/ruby-capstone#16]
### Team Size

- We are a team of 3 people.

   - @Tekhlay  - Team member 3 
  - @houdamzari - Team member 2 
  - @ohyajk -  Team member 1 

Link to Github Project :- https://github.com/ohyajk/ruby-capstone/projects/1

**Comment by Davidosky007** [comment]
Hi @Tekhlay @ohyajk @houdamzari 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Well created board 👍 
* All necessary team info provided 👍 

## Required Changes ♻️
* Kindly assign points evenly amongst the team [As stated in the requirement here ](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the,should%20have%20assignees.)
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hello team👋,

_This is an additional review as a result of the second opinion request._

I have observed that the difference in points between the team members is less than five points.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 

Congratulations! 🎉 

## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ohyajk** [comment]
Thank you @Davidosky007 for your review. I want to extend my regards to @medaminedev66 for quick resolution and @prolajumokeoni for approving my project. A big thanks to my peers @houdamzari and @Tekhlay for collaborating on this beautiful project.
